### PR TITLE
Add RFC: Improve the projectors and the multiview window

### PR DESCRIPTION
**Pull request by Bennik2000**
# Summary
Improve the usability and add more freedom for customization of projectors and the multiview window 

# Motivation
The projectors and the multiview windows are quite useful but do not provide much options for customization. 

# [Read RFC](https://github.com/Bennik2000/rfcs/blob/improve-multiview-and-projectors/accepted/0024-improve-multiview-and-projectors.md)

### CODE REVIEW

**Comment by univrsal** [comment]
When I was playing around with the projector code I had some additional ideas, so I'll just add them here.
Since the multiview is a grid, the user can right click on each cell of the grid and select what source or scene they want it to display (including the preview and program). There would also be an option to drag over multiple grid cells and then right click which would then display the source or scene spanning over the selected cells. This would make the multiview a lot more dynamic, but probably also a bit more complicated. By default the grid would probably be populated the same way it has been so it would be consistent with the current behavior.
I also thought it would be nice if the multiview could show more than just scenes and sources, for example audio levels or stream statistics, which would mean that a cell could also be populated with custom widgets, which handle the rendering.
These features might be a bit overkill but I thought I'd suggest them regardless.

**Comment by unknowndomain** [comment]
I agree that the multiview could do with more configuration options and the idea of a grid is really nice because assuming your output is 16:9 and most monitors are 16:9 or 10 then having 16:9 ratio cells would make scaling and reorganising things really nice.

It would make sense to allow multiple multiviews so that you could have a three monitor setup, 1 for OBS, one for a grid of sources and one for a program/preview preview for example.

**Comment by I3ordo** [comment]
Well i am looking forward to these, very needed improvements imo. You know the OBS layout is flexible, but have some shortcomings in very unexpected ways.
 for ex. 
Cant have fully vertical panels if you put any "dockable" under  or below the preview window
cant dock projectors
have borderless projectors.
Of course things seem too grim if you word it like this, in truth OBS is love!

**Comment by Fenrirthviti** [comment]
Just for clarification, the limitations you listed are limitations of Qt, not OBS (save dockable projectors, we could probably do that).

**Comment by univrsal** [comment]
Just wanted to give a little update, I've implemented some of the features for the multiview I mentioned in a [separate plugin](https://obsproject.com/forum/resources/durchblick.1484/).

**Comment by Fenrirthviti** [comment]
After internal discussion, we feel that the additional functionality provided by the plugin is exactly the kind of thing people looking for that extra functionality have plugins available to do so.

Moving to Final Comment Period, with Disposition Close.

**Pull request closed without merging**
